### ISSUE TITLE
Incorrect balance in 'TRC-21 Fee Fund'?

### ISSUE THREAD

**Issue by PomodoroToken** [tomochain/tomoissuer#154]
I created a TRC21 token (POMO) and have sent about 94 transactions. TomoIssuer is stating that the 10 TOMO I originally deposited to pay for fees has only reduced to 9.9999999994557 TOMO. Either the fees are not being charged correctly, or TomoIssuer is displaying an incorrect remaining balance.

![TomoIssuer Fees](https://user-images.githubusercontent.com/56785480/67414513-2b8f1e80-f5bb-11e9-907e-15ee133ac1d7.png)

**Comment by thanhson1085** [comment]
It fixed from TomoChain repo
