### ISSUE TITLE
Can not change the fee

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomoissuer#63]
![1](https://user-images.githubusercontent.com/546540/60648627-7cdb9c80-9e6a-11e9-9b0b-acffa8bb542e.PNG)
![2](https://user-images.githubusercontent.com/546540/60648628-7cdb9c80-9e6a-11e9-9f98-2951731c8a6c.PNG)

**Comment by pqv199x** [comment]
Because, tomoissuer is getting abi from tomoscan currently. After issuing a new token. user have to go to tomoscan verify token contract in order to change transaction fee

**Comment by thanhson1085** [comment]
Yep, Should store ABI in TomoIssuer db, only allow insert in the first time
