### ISSUE TITLE
Some changes regarding UI/UX (part 1)

### ISSUE THREAD

**Issue by miketomochain** [tomochain/tomoissuer#68]
**1. Homepage**
The illustration is quite large, just need to downsize it to make the text have more room to get attention
![home page](https://user-images.githubusercontent.com/46370751/60697941-2ed0a280-9f17-11e9-9111-7dd1cd2949b0.png)

**2. Donation page**

![donate](https://user-images.githubusercontent.com/46370751/60697985-6c353000-9f17-11e9-8475-26c14e423872.png)

Change the text as the image above
Fuction: Allow usesr to search token by its name

**3. Issuance page**

![issue token page](https://user-images.githubusercontent.com/46370751/60698051-c3d39b80-9f17-11e9-9977-663a1a15f1b9.png)

Change some texts as the image above and add the notification to check the balance whether its enough

**Comment by pqv199x** [comment]
Changed
